[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.85
blur = true
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[selection]
save_to_clipboard = true
